FROM node:23
RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
RUN git clone https://github.com/yt-dlx/yt-dlx.git
WORKDIR /app/yt-dlx
WORKDIR /app/yt-dlx/package/utils
RUN chmod +x ./Tor.sh && ./Tor.sh
WORKDIR /app/yt-dlx/backend
RUN yarn install
RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]