import singleVideo from "./singleVideo";
import searchVideos from "./searchVideos";
import relatedVideos from "./relatedVideos";
import playlistVideos from "./playlistVideos";
import searchPlaylists from "./searchPlaylists";
import type { singleVideoType } from "./singleVideo";
import type { searchVideosType } from "./searchVideos";
import type { relatedVideosType } from "./relatedVideos";
import type { playlistVideosType } from "./playlistVideos";
import type { searchPlaylistsType } from "./searchPlaylists";
export type { singleVideoType, searchVideosType, relatedVideosType, playlistVideosType, searchPlaylistsType };
var web = { singleVideo, searchVideos, relatedVideos, playlistVideos, searchPlaylists };
export default web;
